OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "sk-38rkK0xdFDDMClm688CbCb0204F64d3d874066CbEf2fE608"

GLMModel:
  model_url: "https://api.xiaoai.plus/v1"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"